# Configuration for our postgresql database

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: simple_api_development
  username: simple_api
  password: veryGoodPassword
  host: localhost

test:
  <<: *default
  database: simple_api_test
  username: simple_api
  password: veryGoodPassword
  host: localhost

production:
  <<: *default
  database: simple_api_production
