# Configuration for our postgresql database

default: &default
  adapter: postgresql
  encoding: unicode
  username: simple_api
  password: veryGoodPassword
  pool: 5

development:
  <<: *default
  database: simple_api_development
  host: localhost

test:
  <<: *default
  database: simple_api_test
  host: localhost

production:
  <<: *default
  database: simple_api_production
  password: <%= ENV['DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
